apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "flight-hotel-app.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: {{ .Values.tlsIssuer }}
spec:
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "flight-hotel-app.fullname" . }}
                port:
                  number: 80
  tls:
    - hosts:
        - {{ .Values.domain }}
      secretName: {{ .Values.appName }}-tls
