apiVersion: v1
kind: Service
metadata:
  name: {{ include "flight-hotel-app.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.appName }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http