apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flight-b2b-new1
  namespace: default
spec:
  interval: 1m
  releaseName: flight-b2b-new1
  chart:
    spec:
      chart: ./helm-charts/flight-hotel-app
      sourceRef:
        kind: GitRepository
        name: flight-hotel-app
        namespace: flux-system
  values:
    appName: "flight-b2b-new1"
    image:
      repository: "yourrepo/flight-app"
      tag: "latest"
    domain: "flight-b2b-new1.yourdomain.com"
    tlsIssuer: "letsencrypt-prod"
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 10
      cpuUtilization: 60
